import type { Annotation } from '@/types/annotation';
import type { AppState, ColorAdjustment, Tool, UndoEntry, ZoomLevel } from '@/types/app';
import type { OcrLanguage, OcrPageResult } from '@/types/ocr';
import type { SourceFormat } from '@/types/page';
import type { Dispatch, SetStateAction } from 'react';

export type SetState = Dispatch<SetStateAction<AppState>>;

export const MAX_UNDO = 50;

export interface PagePickerState {
  sourceId: string;
  sourceFormat: SourceFormat;
  pageCount: number;
  mode: 'insert' | 'replace';
  targetIndex: number;
}

export interface AppContextValue extends AppState {
  pageCount: number;
  currentPage: number;
  currentPageId: string | null;
  setActiveTool: (tool: Tool) => void;
  setZoom: (zoom: ZoomLevel) => void;
  toggleSidebar: () => void;
  setCurrentPageIndex: (index: number) => void;
  openDocument: (filename: string, format: string, data: Uint8Array) => Promise<void>;
  closeDocument: () => void;
  newDocument: () => void;
  toggleSearchBar: () => void;
  closeSearchBar: () => void;
  setSearchQuery: (query: string) => void;
  toggleCaseSensitive: () => void;
  openGoToPageDialog: () => void;
  closeGoToPageDialog: () => void;
  openExportDialog: () => void;
  closeExportDialog: () => void;
  openResizeDialog: () => void;
  closeResizeDialog: () => void;
  openInspectorDialog: () => void;
  closeInspectorDialog: () => void;
  openSignaturePadDialog: () => void;
  closeSignaturePadDialog: () => void;
  openPasswordDialog: () => void;
  closePasswordDialog: () => void;
  openOcrDialog: () => void;
  closeOcrDialog: () => void;
  openDeletePageDialog: () => void;
  closeDeletePageDialog: () => void;
  openAboutDialog: () => void;
  closeAboutDialog: () => void;
  openTetrisDialog: () => void;
  closeTetrisDialog: () => void;
  openCompressPdfDialog: () => void;
  closeCompressPdfDialog: () => void;
  addAnnotation: (annotation: Annotation) => void;
  updateAnnotation: (id: string, updates: Partial<Annotation>) => void;
  deleteAnnotation: (id: string) => void;
  deleteSelectedAnnotations: () => void;
  selectAnnotation: (id: string | null) => void;
  selectAllAnnotations: () => void;
  bringToFront: (id: string) => void;
  sendToBack: (id: string) => void;
  getSelectedAnnotation: () => Annotation | null;
  rotatePage: (pageIndex: number, direction: 'left' | 'right') => void;
  flipPage: (pageIndex: number, axis: 'horizontal' | 'vertical') => void;
  deletePage: (pageIndex: number) => void;
  deleteCurrentPage: () => void;
  insertPageAfter: (pageIndex: number) => void;
  reorderPages: (fromIndex: number, toIndex: number) => void;
  setSelectedPageIndices: (indices: number[]) => void;
  selectAllPages: () => void;
  clearPageSelection: () => void;
  handlePageClick: (index: number, ctrlKey: boolean, shiftKey: boolean) => void;
  deleteSelectedPages: () => void;
  rotateSelectedPages: (direction: 'left' | 'right') => void;
  insertPagesFromFile: (afterIndex: number, file: File) => Promise<void>;
  replacePageWithFile: (pageIndex: number, file: File) => Promise<void>;
  insertPagesFromSource: (afterIndex: number, sourceId: string, pageIndices: number[], sourceFormat: 'pdf' | 'image') => void;
  replacePageFromSource: (targetIndex: number, sourceId: string, pageIndex: number, sourceFormat: 'pdf' | 'image') => void;
  pagePickerState: PagePickerState | null;
  openPagePickerDialog: (state: PagePickerState) => void;
  closePagePickerDialog: () => void;
  setCropMode: (active: boolean) => void;
  setCropRect: (rect: AppState['cropRect']) => void;
  applyCrop: () => void;
  undo: () => void;
  redo: () => void;
  pushUndo: (entry: UndoEntry) => void;
  copyAnnotation: () => void;
  cutAnnotation: () => void;
  pasteAnnotation: () => void;
  setViewMode: (mode: 'single' | 'contact-sheet') => void;
  toggleViewMode: () => void;
  toggleSketchRecognition: () => void;
  setMaskRect: (rect: AppState['maskRect']) => void;
  clearMask: () => void;
  setLoupePosition: (pos: { x: number; y: number } | null) => void;
  setLoupeMagnification: (mag: number) => void;
  setColorAdjustment: (adj: Partial<ColorAdjustment>) => void;
  resetColorAdjustment: () => void;
  toggleColorAdjustmentPanel: () => void;
  fitWidth: () => void;
  fitPage: () => void;
  searchNext: () => void;
  searchPrevious: () => void;
  toggleFullscreen: () => void;
  setFormFieldValue: (fieldId: string, value: string) => void;
  toggleFormMode: () => void;
  setPrintMode: (active: boolean) => void;
  setBatchProgress: (progress: number | null) => void;
  setOcrLanguage: (language: OcrLanguage) => void;
  setOcrResult: (pageId: string, result: OcrPageResult) => void;
  clearOcrResult: (pageId: string) => void;
  clearAllOcrResults: () => void;
  setOcrProcessing: (isProcessing: boolean) => void;
  setOcrProgress: (progress: { current: number; total: number } | null) => void;
  compressPages: (preset: 'email' | 'compact' | 'light', runOcr: boolean, onProgress: (current: number, total: number, phase: string) => void, signal: AbortSignal) => Promise<void>;
}
