import type { AppState } from '@/types/app';
import type { OcrLanguage } from '@/types/ocr';

export const INITIAL_APP_STATE: AppState = {
  isDocumentOpen: false,
  isDocumentLoading: false,
  documentSessionId: null,
  filename: null,
  format: null,
  pages: [],
  currentPageIndex: 0,
  selectedPageIndices: [0],
  zoom: 1.0,
  activeTool: 'selection',
  isSidebarVisible: true,
  isFullscreen: false,
  isSearchBarVisible: false,
  searchQuery: '',
  isCaseSensitive: false,
  searchMatchIndex: 0,
  searchMatchTotal: 0,
  searchMatches: [],
  isGoToPageDialogOpen: false,
  isExportDialogOpen: false,
  isResizeDialogOpen: false,
  isInspectorDialogOpen: false,
  isSignaturePadOpen: false,
  isPasswordDialogOpen: false,
  isOcrDialogOpen: false,
  isDeletePageDialogOpen: false,
  isAboutDialogOpen: false,
  isTetrisDialogOpen: false,
  isCompressPdfDialogOpen: false,
  isPagePickerDialogOpen: false,
  isCropMode: false,
  annotations: {},
  selectedAnnotationId: null,
  selectedAnnotationIds: [],
  undoStack: [],
  redoStack: [],
  clipboard: null,
  viewMode: 'single',
  isSketchRecognitionEnabled: false,
  maskRect: null,
  loupePosition: null,
  loupeMagnification: 2,
  colorAdjustment: {
    exposure: 0,
    contrast: 0,
    highlights: 0,
    shadows: 0,
    saturation: 0,
    temperature: 0,
    tint: 0,
    sharpness: 0,
    sepia: 0,
  },
  isColorAdjustmentPanelOpen: false,
  isPrintMode: false,
  cropRect: null,
  formFields: [],
  isFormMode: false,
  pdfLinks: [],
  batchProgress: null,
  ocrResults: {},
  ocrLanguage: 'latin' as OcrLanguage,
  isOcrProcessing: false,
  ocrProgress: null,
  nativeText: {},
};
